# Generated by Django 4.2 on 2023-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='full_name',
            field=models.CharField(default='prem kumar', max_length=150),
        ),
    ]
