# Generated by Django 4.2 on 2023-05-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0002_passenger_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='full_name',
        ),
    ]
